post http://localhost:5000/training
Content-Type:  application/json

{
    "bot": "Gordo",
    "intent": {
        "name":"Saudação",
        "content": [
            "Oi",
            "Oi, tudo bem?",
            "Olá",
            "Olá, em que posso ajudar?",
            "e ai",
            "Opa, qual a boa?"
        ]
    }
}